/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ChatId = IDL.Nat;
export const MessageRole = IDL.Variant({
  'user' : IDL.Null,
  'assistant' : IDL.Null,
});
export const InputType = IDL.Variant({
  'voice' : IDL.Null,
  'text' : IDL.Null,
  'image' : IDL.Null,
});
export const MessageId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const MessageInfo = IDL.Record({
  'id' : MessageId,
  'inputType' : InputType,
  'content' : IDL.Text,
  'role' : MessageRole,
  'timestamp' : Timestamp,
  'chatId' : ChatId,
});
export const Subject = IDL.Variant({
  'biology' : IDL.Null,
  'other' : IDL.Null,
  'math' : IDL.Null,
  'history' : IDL.Null,
  'language' : IDL.Null,
  'chemistry' : IDL.Null,
  'physics' : IDL.Null,
});
export const ChatInfo = IDL.Record({
  'id' : ChatId,
  'title' : IDL.Text,
  'subject' : Subject,
  'userId' : IDL.Principal,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
});
export const ChatWithMessages = IDL.Record({
  'messages' : IDL.Vec(MessageInfo),
  'chat' : ChatInfo,
});
export const SubmitDoubtResult = IDL.Record({
  'subject' : Subject,
  'aiMessageId' : MessageId,
  'userMessageId' : MessageId,
  'aiResponse' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addMessage' : IDL.Func(
      [ChatId, MessageRole, IDL.Text, InputType],
      [IDL.Opt(MessageId)],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createChat' : IDL.Func([IDL.Text], [ChatId, IDL.Text], []),
  'deleteChat' : IDL.Func([ChatId], [IDL.Bool], []),
  'deleteMessage' : IDL.Func([MessageId], [IDL.Bool], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChat' : IDL.Func([ChatId], [IDL.Opt(ChatWithMessages)], ['query']),
  'getUserChats' : IDL.Func([], [IDL.Vec(ChatInfo)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'submitDoubt' : IDL.Func(
      [ChatId, InputType, IDL.Text, IDL.Opt(IDL.Text)],
      [SubmitDoubtResult],
      [],
    ),
  'transformGroq' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ChatId = IDL.Nat;
  const MessageRole = IDL.Variant({
    'user' : IDL.Null,
    'assistant' : IDL.Null,
  });
  const InputType = IDL.Variant({
    'voice' : IDL.Null,
    'text' : IDL.Null,
    'image' : IDL.Null,
  });
  const MessageId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const MessageInfo = IDL.Record({
    'id' : MessageId,
    'inputType' : InputType,
    'content' : IDL.Text,
    'role' : MessageRole,
    'timestamp' : Timestamp,
    'chatId' : ChatId,
  });
  const Subject = IDL.Variant({
    'biology' : IDL.Null,
    'other' : IDL.Null,
    'math' : IDL.Null,
    'history' : IDL.Null,
    'language' : IDL.Null,
    'chemistry' : IDL.Null,
    'physics' : IDL.Null,
  });
  const ChatInfo = IDL.Record({
    'id' : ChatId,
    'title' : IDL.Text,
    'subject' : Subject,
    'userId' : IDL.Principal,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
  });
  const ChatWithMessages = IDL.Record({
    'messages' : IDL.Vec(MessageInfo),
    'chat' : ChatInfo,
  });
  const SubmitDoubtResult = IDL.Record({
    'subject' : Subject,
    'aiMessageId' : MessageId,
    'userMessageId' : MessageId,
    'aiResponse' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addMessage' : IDL.Func(
        [ChatId, MessageRole, IDL.Text, InputType],
        [IDL.Opt(MessageId)],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createChat' : IDL.Func([IDL.Text], [ChatId, IDL.Text], []),
    'deleteChat' : IDL.Func([ChatId], [IDL.Bool], []),
    'deleteMessage' : IDL.Func([MessageId], [IDL.Bool], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChat' : IDL.Func([ChatId], [IDL.Opt(ChatWithMessages)], ['query']),
    'getUserChats' : IDL.Func([], [IDL.Vec(ChatInfo)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'submitDoubt' : IDL.Func(
        [ChatId, InputType, IDL.Text, IDL.Opt(IDL.Text)],
        [SubmitDoubtResult],
        [],
      ),
    'transformGroq' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };