/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ChatId = bigint;
export interface ChatInfo {
  'id' : ChatId,
  'title' : string,
  'subject' : Subject,
  'userId' : Principal,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
}
export interface ChatWithMessages {
  'messages' : Array<MessageInfo>,
  'chat' : ChatInfo,
}
export type InputType = { 'voice' : null } |
  { 'text' : null } |
  { 'image' : null };
export type MessageId = bigint;
export interface MessageInfo {
  'id' : MessageId,
  'inputType' : InputType,
  'content' : string,
  'role' : MessageRole,
  'timestamp' : Timestamp,
  'chatId' : ChatId,
}
export type MessageRole = { 'user' : null } |
  { 'assistant' : null };
export type Subject = { 'biology' : null } |
  { 'other' : null } |
  { 'math' : null } |
  { 'history' : null } |
  { 'language' : null } |
  { 'chemistry' : null } |
  { 'physics' : null };
export interface SubmitDoubtResult {
  'subject' : Subject,
  'aiMessageId' : MessageId,
  'userMessageId' : MessageId,
  'aiResponse' : string,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addMessage' : ActorMethod<
    [ChatId, MessageRole, string, InputType],
    [] | [MessageId]
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createChat' : ActorMethod<[string], [ChatId, string]>,
  'deleteChat' : ActorMethod<[ChatId], boolean>,
  'deleteMessage' : ActorMethod<[MessageId], boolean>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChat' : ActorMethod<[ChatId], [] | [ChatWithMessages]>,
  'getUserChats' : ActorMethod<[], Array<ChatInfo>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'submitDoubt' : ActorMethod<
    [ChatId, InputType, string, [] | [string]],
    SubmitDoubtResult
  >,
  'transformGroq' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];