/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type ChatId = bigint;
export interface MessageInfo {
    id: MessageId;
    inputType: InputType;
    content: string;
    role: MessageRole;
    timestamp: Timestamp;
    chatId: ChatId;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ChatInfo {
    id: ChatId;
    title: string;
    subject: Subject;
    userId: Principal;
    createdAt: Timestamp;
    updatedAt: Timestamp;
}
export interface SubmitDoubtResult {
    subject: Subject;
    aiMessageId: MessageId;
    userMessageId: MessageId;
    aiResponse: string;
}
export type MessageId = bigint;
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface ChatWithMessages {
    messages: Array<MessageInfo>;
    chat: ChatInfo;
}
export enum InputType {
    voice = "voice",
    text = "text",
    image = "image"
}
export enum MessageRole {
    user = "user",
    assistant = "assistant"
}
export enum Subject {
    biology = "biology",
    other = "other",
    math = "math",
    history = "history",
    language = "language",
    chemistry = "chemistry",
    physics = "physics"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addMessage(chatId: ChatId, role: MessageRole, content: string, inputType: InputType): Promise<MessageId | null>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createChat(firstQuestion: string): Promise<[ChatId, string]>;
    deleteChat(chatId: ChatId): Promise<boolean>;
    deleteMessage(messageId: MessageId): Promise<boolean>;
    getCallerUserRole(): Promise<UserRole>;
    getChat(chatId: ChatId): Promise<ChatWithMessages | null>;
    getUserChats(): Promise<Array<ChatInfo>>;
    isCallerAdmin(): Promise<boolean>;
    submitDoubt(chatId: ChatId, inputType: InputType, content: string, imageKey: string | null): Promise<SubmitDoubtResult>;
    transformGroq(input: TransformationInput): Promise<TransformationOutput>;
}
import type { ChatId as _ChatId, ChatInfo as _ChatInfo, ChatWithMessages as _ChatWithMessages, InputType as _InputType, MessageId as _MessageId, MessageInfo as _MessageInfo, MessageRole as _MessageRole, Subject as _Subject, SubmitDoubtResult as _SubmitDoubtResult, Timestamp as _Timestamp, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addMessage(arg0: ChatId, arg1: MessageRole, arg2: string, arg3: InputType): Promise<MessageId | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addMessage(arg0, to_candid_MessageRole_n1(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_InputType_n3(this._uploadFile, this._downloadFile, arg3));
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMessage(arg0, to_candid_MessageRole_n1(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_InputType_n3(this._uploadFile, this._downloadFile, arg3));
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createChat(arg0: string): Promise<[ChatId, string]> {
        if (this.processError) {
            try {
                const result = await this.actor.createChat(arg0);
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChat(arg0);
            return [
                result[0],
                result[1]
            ];
        }
    }
    async deleteChat(arg0: ChatId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChat(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChat(arg0);
            return result;
        }
    }
    async deleteMessage(arg0: MessageId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMessage(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChat(arg0: ChatId): Promise<ChatWithMessages | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChat(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChat(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserChats(): Promise<Array<ChatInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserChats();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserChats();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async submitDoubt(arg0: ChatId, arg1: InputType, arg2: string, arg3: string | null): Promise<SubmitDoubtResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitDoubt(arg0, to_candid_InputType_n3(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n25(this._uploadFile, this._downloadFile, arg3));
                return from_candid_SubmitDoubtResult_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitDoubt(arg0, to_candid_InputType_n3(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n25(this._uploadFile, this._downloadFile, arg3));
            return from_candid_SubmitDoubtResult_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async transformGroq(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transformGroq(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformGroq(arg0);
            return result;
        }
    }
}
function from_candid_ChatInfo_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatInfo): ChatInfo {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_ChatWithMessages_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatWithMessages): ChatWithMessages {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_InputType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InputType): InputType {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_MessageInfo_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageInfo): MessageInfo {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_MessageRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageRole): MessageRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Subject_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subject): Subject {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_SubmitDoubtResult_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmitDoubtResult): SubmitDoubtResult {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChatWithMessages]): ChatWithMessages | null {
    return value.length === 0 ? null : from_candid_ChatWithMessages_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MessageId]): MessageId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    messages: Array<_MessageInfo>;
    chat: _ChatInfo;
}): {
    messages: Array<MessageInfo>;
    chat: ChatInfo;
} {
    return {
        messages: from_candid_vec_n13(_uploadFile, _downloadFile, value.messages),
        chat: from_candid_ChatInfo_n20(_uploadFile, _downloadFile, value.chat)
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MessageId;
    inputType: _InputType;
    content: string;
    role: _MessageRole;
    timestamp: _Timestamp;
    chatId: _ChatId;
}): {
    id: MessageId;
    inputType: InputType;
    content: string;
    role: MessageRole;
    timestamp: Timestamp;
    chatId: ChatId;
} {
    return {
        id: value.id,
        inputType: from_candid_InputType_n16(_uploadFile, _downloadFile, value.inputType),
        content: value.content,
        role: from_candid_MessageRole_n18(_uploadFile, _downloadFile, value.role),
        timestamp: value.timestamp,
        chatId: value.chatId
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ChatId;
    title: string;
    subject: _Subject;
    userId: Principal;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
}): {
    id: ChatId;
    title: string;
    subject: Subject;
    userId: Principal;
    createdAt: Timestamp;
    updatedAt: Timestamp;
} {
    return {
        id: value.id,
        title: value.title,
        subject: from_candid_Subject_n22(_uploadFile, _downloadFile, value.subject),
        userId: value.userId,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subject: _Subject;
    aiMessageId: _MessageId;
    userMessageId: _MessageId;
    aiResponse: string;
}): {
    subject: Subject;
    aiMessageId: MessageId;
    userMessageId: MessageId;
    aiResponse: string;
} {
    return {
        subject: from_candid_Subject_n22(_uploadFile, _downloadFile, value.subject),
        aiMessageId: value.aiMessageId,
        userMessageId: value.userMessageId,
        aiResponse: value.aiResponse
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    voice: null;
} | {
    text: null;
} | {
    image: null;
}): InputType {
    return "voice" in value ? InputType.voice : "text" in value ? InputType.text : "image" in value ? InputType.image : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: null;
} | {
    assistant: null;
}): MessageRole {
    return "user" in value ? MessageRole.user : "assistant" in value ? MessageRole.assistant : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    biology: null;
} | {
    other: null;
} | {
    math: null;
} | {
    history: null;
} | {
    language: null;
} | {
    chemistry: null;
} | {
    physics: null;
}): Subject {
    return "biology" in value ? Subject.biology : "other" in value ? Subject.other : "math" in value ? Subject.math : "history" in value ? Subject.history : "language" in value ? Subject.language : "chemistry" in value ? Subject.chemistry : "physics" in value ? Subject.physics : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MessageInfo>): Array<MessageInfo> {
    return value.map((x)=>from_candid_MessageInfo_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatInfo>): Array<ChatInfo> {
    return value.map((x)=>from_candid_ChatInfo_n20(_uploadFile, _downloadFile, x));
}
function to_candid_InputType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InputType): _InputType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_MessageRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageRole): _MessageRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageRole): {
    user: null;
} | {
    assistant: null;
} {
    return value == MessageRole.user ? {
        user: null
    } : value == MessageRole.assistant ? {
        assistant: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InputType): {
    voice: null;
} | {
    text: null;
} | {
    image: null;
} {
    return value == InputType.voice ? {
        voice: null
    } : value == InputType.text ? {
        text: null
    } : value == InputType.image ? {
        image: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
